# Site settings
title: Gabo - Front End Engineer
nickname : Gabo
email: tuxgabo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Front End engineer topics and life style notes
pygments: true
permalink: /:year/:month/:title
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gaboramirez.com" # the base hostname & protocol for your site
twitter_username: adictovirtual
github_username:  adictovirtual

# Build settings
markdown: kramdown
