# Site settings
title: Juan Gabriel Ramirez
email: tuxgabo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tecnologias Front end y buenas practicas a la hora de hacer codigo
  Todo esto sera abordado en este blog totalmente en español.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: adictovirtual
github_username:  adictovirtual

# Build settings
markdown: kramdown
