# Site settings
title: juan gabriel ramirez cruz - Nomada Digital
nickname : Gabo
email: tuxgabo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Bitacora de un Nomada
permalink: /:year/:month/:title
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gaboramirez.com" # the base hostname & protocol for your site
twitter_username: adictovirtual
github_username:  adictovirtual

# Build settings
markdown: kramdown
